server :
 port : 8077
spring :
 datasource :
  druid :
   url : jdbc:mysql://localhost:3306/test?characterEncoding=utf-8
   driver-class-name : com.mysql.cj.jdbc.Driver
   username : root
   password : 123456
 banner:
   location: classpath:banner/banner.txt
mybatis:
 mapper-locations: classpath:mapper/*.xml
 type-aliases-package: com.springboot.demo.entity
